services:
  web:
    build:
      context: .
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

  pgadmin:
    image: dpage/pgadmin4:9.0
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=mangjoe@inasal.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin-password
    depends_on:
      - db
    ports:
      - 5050:80
    secrets:
      - pgadmin-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  db:
    image: postgres:15.10
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mangjoe_db
      - POSTGRES_USER=mangjoe
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "mangjoe", "-d", "mangjoe_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  db-data:
  pgadmin-data:

secrets:
  db-password:
    file: db/password.txt
  pgadmin-password:
    file: db/password.txt