services:
  web:
    build:
      context: .
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

  db:
    image: postgres:15.10
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mangjoe_db
      - POSTGRES_USER=mangjoe
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready -U mangjoe" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt